# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/window.ui'
#
# Created: Wed May 26 20:07:16 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(900, 550)
        Dialog.setMinimumSize(QtCore.QSize(900, 550))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout_18 = QtGui.QGridLayout(Dialog)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_7)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.label_7 = QtGui.QLabel(self.tab_7)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.label_4 = QtGui.QLabel(self.tab_7)
        self.label_4.setTextFormat(QtCore.Qt.RichText)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.gridLayout_9.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_16 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_15 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_15.addWidget(self.label_8)
        self.conf_host = QtGui.QLineEdit(self.groupBox_2)
        self.conf_host.setEnabled(True)
        self.conf_host.setAlignment(QtCore.Qt.AlignCenter)
        self.conf_host.setReadOnly(False)
        self.conf_host.setObjectName("conf_host")
        self.horizontalLayout_15.addWidget(self.conf_host)
        self.conf_host_all = QtGui.QPushButton(self.groupBox_2)
        self.conf_host_all.setObjectName("conf_host_all")
        self.horizontalLayout_15.addWidget(self.conf_host_all)
        self.verticalLayout_16.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_10 = QtGui.QLabel(self.groupBox_8)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.label_9 = QtGui.QLabel(self.groupBox_8)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.label_12 = QtGui.QLabel(self.groupBox_8)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.conf_mysql = QtGui.QLineEdit(self.groupBox_8)
        self.conf_mysql.setEnabled(True)
        self.conf_mysql.setText("")
        self.conf_mysql.setAlignment(QtCore.Qt.AlignCenter)
        self.conf_mysql.setReadOnly(False)
        self.conf_mysql.setObjectName("conf_mysql")
        self.verticalLayout_5.addWidget(self.conf_mysql)
        self.conf_route = QtGui.QLineEdit(self.groupBox_8)
        self.conf_route.setEnabled(True)
        self.conf_route.setText("")
        self.conf_route.setAlignment(QtCore.Qt.AlignCenter)
        self.conf_route.setReadOnly(False)
        self.conf_route.setObjectName("conf_route")
        self.verticalLayout_5.addWidget(self.conf_route)
        self.conf_upload = QtGui.QLineEdit(self.groupBox_8)
        self.conf_upload.setEnabled(True)
        self.conf_upload.setText("")
        self.conf_upload.setAlignment(QtCore.Qt.AlignCenter)
        self.conf_upload.setReadOnly(False)
        self.conf_upload.setObjectName("conf_upload")
        self.verticalLayout_5.addWidget(self.conf_upload)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.gridLayout_10.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.horizontalLayout_11.addWidget(self.groupBox_8)
        self.groupBox_9 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        spacerItem2 = QtGui.QSpacerItem(20, 17, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem2)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_11 = QtGui.QLabel(self.groupBox_9)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_13.addWidget(self.label_11)
        self.label_14 = QtGui.QLabel(self.groupBox_9)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_13.addWidget(self.label_14)
        self.horizontalLayout_10.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.conf_db = QtGui.QLineEdit(self.groupBox_9)
        self.conf_db.setEnabled(True)
        self.conf_db.setInputMask("")
        self.conf_db.setText("")
        self.conf_db.setAlignment(QtCore.Qt.AlignCenter)
        self.conf_db.setReadOnly(False)
        self.conf_db.setObjectName("conf_db")
        self.verticalLayout_14.addWidget(self.conf_db)
        self.conf_user = QtGui.QLineEdit(self.groupBox_9)
        self.conf_user.setEnabled(True)
        self.conf_user.setInputMask("")
        self.conf_user.setText("")
        self.conf_user.setAlignment(QtCore.Qt.AlignCenter)
        self.conf_user.setReadOnly(False)
        self.conf_user.setObjectName("conf_user")
        self.verticalLayout_14.addWidget(self.conf_user)
        self.horizontalLayout_10.addLayout(self.verticalLayout_14)
        self.verticalLayout_15.addLayout(self.horizontalLayout_10)
        spacerItem3 = QtGui.QSpacerItem(20, 17, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem3)
        self.gridLayout.addLayout(self.verticalLayout_15, 0, 0, 1, 1)
        self.horizontalLayout_11.addWidget(self.groupBox_9)
        self.verticalLayout_16.addLayout(self.horizontalLayout_11)
        self.conf_reset = QtGui.QPushButton(self.groupBox_2)
        self.conf_reset.setObjectName("conf_reset")
        self.verticalLayout_16.addWidget(self.conf_reset)
        self.gridLayout_15.addLayout(self.verticalLayout_16, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.start = QtGui.QPushButton(self.tab_2)
        self.start.setObjectName("start")
        self.horizontalLayout_3.addWidget(self.start)
        self.stop = QtGui.QPushButton(self.tab_2)
        self.stop.setEnabled(False)
        self.stop.setObjectName("stop")
        self.horizontalLayout_3.addWidget(self.stop)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.gridLayout_16.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_11 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_3 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.host_list = QtGui.QTableView(self.groupBox_3)
        self.host_list.setEnabled(False)
        self.host_list.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.host_list.setTextElideMode(QtCore.Qt.ElideLeft)
        self.host_list.setObjectName("host_list")
        self.host_list.horizontalHeader().setVisible(True)
        self.host_list.horizontalHeader().setStretchLastSection(True)
        self.host_list.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.host_list, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtGui.QGroupBox(self.tab_6)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.host_ip = QtGui.QLineEdit(self.groupBox)
        self.host_ip.setEnabled(False)
        self.host_ip.setAlignment(QtCore.Qt.AlignCenter)
        self.host_ip.setReadOnly(False)
        self.host_ip.setObjectName("host_ip")
        self.horizontalLayout_2.addWidget(self.host_ip)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.host_port = QtGui.QLineEdit(self.groupBox)
        self.host_port.setEnabled(False)
        self.host_port.setAlignment(QtCore.Qt.AlignCenter)
        self.host_port.setReadOnly(False)
        self.host_port.setObjectName("host_port")
        self.horizontalLayout.addWidget(self.host_port)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.host_connect = QtGui.QPushButton(self.groupBox)
        self.host_connect.setEnabled(False)
        self.host_connect.setObjectName("host_connect")
        self.verticalLayout.addWidget(self.host_connect)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.host_disconnect = QtGui.QPushButton(self.tab_6)
        self.host_disconnect.setEnabled(False)
        self.host_disconnect.setObjectName("host_disconnect")
        self.verticalLayout_2.addWidget(self.host_disconnect)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.gridLayout_11.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_12 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.file_list = QtGui.QTableView(self.tab_3)
        self.file_list.setEnabled(False)
        self.file_list.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.file_list.setTextElideMode(QtCore.Qt.ElideLeft)
        self.file_list.setObjectName("file_list")
        self.file_list.horizontalHeader().setVisible(True)
        self.file_list.horizontalHeader().setDefaultSectionSize(400)
        self.file_list.horizontalHeader().setMinimumSectionSize(400)
        self.file_list.horizontalHeader().setStretchLastSection(True)
        self.file_list.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.file_list)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.file_add = QtGui.QPushButton(self.tab_3)
        self.file_add.setEnabled(False)
        self.file_add.setObjectName("file_add")
        self.horizontalLayout_5.addWidget(self.file_add)
        self.file_del = QtGui.QPushButton(self.tab_3)
        self.file_del.setEnabled(False)
        self.file_del.setObjectName("file_del")
        self.horizontalLayout_5.addWidget(self.file_del)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.gridLayout_12.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_13 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.groupBox_6 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtGui.QLabel(self.groupBox_6)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.sea_mask = QtGui.QLineEdit(self.groupBox_6)
        self.sea_mask.setEnabled(False)
        self.sea_mask.setAlignment(QtCore.Qt.AlignCenter)
        self.sea_mask.setObjectName("sea_mask")
        self.horizontalLayout_7.addWidget(self.sea_mask)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtGui.QLabel(self.groupBox_6)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.sea_size_op = QtGui.QComboBox(self.groupBox_6)
        self.sea_size_op.setEnabled(False)
        self.sea_size_op.setObjectName("sea_size_op")
        self.sea_size_op.addItem("")
        self.sea_size_op.addItem("")
        self.sea_size_op.addItem("")
        self.sea_size_op.addItem("")
        self.sea_size_op.addItem("")
        self.sea_size_op.addItem("")
        self.horizontalLayout_8.addWidget(self.sea_size_op)
        self.sea_size = QtGui.QLineEdit(self.groupBox_6)
        self.sea_size.setEnabled(False)
        self.sea_size.setAlignment(QtCore.Qt.AlignCenter)
        self.sea_size.setObjectName("sea_size")
        self.horizontalLayout_8.addWidget(self.sea_size)
        self.label_6 = QtGui.QLabel(self.groupBox_6)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.sea_run = QtGui.QPushButton(self.groupBox_6)
        self.sea_run.setEnabled(False)
        self.sea_run.setObjectName("sea_run")
        self.verticalLayout_10.addWidget(self.sea_run)
        self.gridLayout_6.addLayout(self.verticalLayout_10, 0, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.groupBox_6)
        self.groupBox_7 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.sea_res = QtGui.QTableView(self.groupBox_7)
        self.sea_res.setEnabled(False)
        self.sea_res.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.sea_res.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.sea_res.setTextElideMode(QtCore.Qt.ElideLeft)
        self.sea_res.setObjectName("sea_res")
        self.sea_res.horizontalHeader().setStretchLastSection(True)
        self.sea_res.verticalHeader().setVisible(False)
        self.verticalLayout_11.addWidget(self.sea_res)
        self.sea_down = QtGui.QPushButton(self.groupBox_7)
        self.sea_down.setEnabled(False)
        self.sea_down.setObjectName("sea_down")
        self.verticalLayout_11.addWidget(self.sea_down)
        self.gridLayout_7.addLayout(self.verticalLayout_11, 0, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.groupBox_7)
        self.gridLayout_13.addLayout(self.verticalLayout_12, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_14 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_4 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.down_list = QtGui.QTableView(self.groupBox_4)
        self.down_list.setEnabled(False)
        self.down_list.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.down_list.setTextElideMode(QtCore.Qt.ElideLeft)
        self.down_list.setObjectName("down_list")
        self.down_list.horizontalHeader().setDefaultSectionSize(400)
        self.down_list.horizontalHeader().setMinimumSectionSize(400)
        self.down_list.horizontalHeader().setStretchLastSection(True)
        self.down_list.verticalHeader().setVisible(False)
        self.verticalLayout_7.addWidget(self.down_list)
        self.down_del = QtGui.QPushButton(self.groupBox_4)
        self.down_del.setEnabled(False)
        self.down_del.setObjectName("down_del")
        self.verticalLayout_7.addWidget(self.down_del)
        self.gridLayout_4.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.groupBox_4)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.down_finish = QtGui.QTableView(self.groupBox_5)
        self.down_finish.setEnabled(False)
        self.down_finish.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.down_finish.setTextElideMode(QtCore.Qt.ElideLeft)
        self.down_finish.setFocusPolicy(QtCore.Qt.NoFocus)
        self.down_finish.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.down_finish.setObjectName("down_finish")
        self.down_finish.horizontalHeader().setStretchLastSection(True)
        self.down_finish.verticalHeader().setVisible(False)
        self.verticalLayout_8.addWidget(self.down_finish)
        self.down_finish_clear = QtGui.QPushButton(self.groupBox_5)
        self.down_finish_clear.setEnabled(False)
        self.down_finish_clear.setAccessibleName("")
        self.down_finish_clear.setObjectName("down_finish_clear")
        self.verticalLayout_8.addWidget(self.down_finish_clear)
        self.gridLayout_5.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.groupBox_5)
        self.gridLayout_14.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.gridLayout_8.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem6)
        self.label_13 = QtGui.QLabel(Dialog)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_16.addWidget(self.label_13)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem7)
        self.gridLayout_8.addLayout(self.horizontalLayout_16, 1, 0, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_8, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.start, QtCore.SIGNAL("clicked()"), Dialog.start_click)
        QtCore.QObject.connect(self.stop, QtCore.SIGNAL("clicked()"), Dialog.stop_click)
        QtCore.QObject.connect(self.conf_host_all, QtCore.SIGNAL("clicked()"), Dialog.conf_host_all_click)
        QtCore.QObject.connect(self.host_connect, QtCore.SIGNAL("clicked()"), Dialog.host_connect_click)
        QtCore.QObject.connect(self.host_disconnect, QtCore.SIGNAL("clicked()"), Dialog.host_disconnect_click)
        QtCore.QObject.connect(self.file_add, QtCore.SIGNAL("clicked()"), Dialog.file_add_click)
        QtCore.QObject.connect(self.file_del, QtCore.SIGNAL("clicked()"), Dialog.file_del_click)
        QtCore.QObject.connect(self.sea_run, QtCore.SIGNAL("clicked()"), Dialog.sea_run_click)
        QtCore.QObject.connect(self.sea_down, QtCore.SIGNAL("clicked()"), Dialog.sea_down_click)
        QtCore.QObject.connect(self.down_finish_clear, QtCore.SIGNAL("clicked()"), Dialog.down_finish_clear_click)
        QtCore.QObject.connect(self.down_del, QtCore.SIGNAL("clicked()"), Dialog.down_del_click)
        QtCore.QObject.connect(Dialog, QtCore.SIGNAL("finished(int)"), Dialog.main_window_close)
        QtCore.QObject.connect(self.conf_reset, QtCore.SIGNAL("clicked()"), Dialog.conf_reset_click)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tabWidget, self.conf_host)
        Dialog.setTabOrder(self.conf_host, self.conf_host_all)
        Dialog.setTabOrder(self.conf_host_all, self.conf_mysql)
        Dialog.setTabOrder(self.conf_mysql, self.conf_route)
        Dialog.setTabOrder(self.conf_route, self.conf_upload)
        Dialog.setTabOrder(self.conf_upload, self.conf_db)
        Dialog.setTabOrder(self.conf_db, self.conf_user)
        Dialog.setTabOrder(self.conf_user, self.conf_reset)
        Dialog.setTabOrder(self.conf_reset, self.start)
        Dialog.setTabOrder(self.start, self.stop)
        Dialog.setTabOrder(self.stop, self.host_list)
        Dialog.setTabOrder(self.host_list, self.host_ip)
        Dialog.setTabOrder(self.host_ip, self.host_port)
        Dialog.setTabOrder(self.host_port, self.host_connect)
        Dialog.setTabOrder(self.host_connect, self.host_disconnect)
        Dialog.setTabOrder(self.host_disconnect, self.file_list)
        Dialog.setTabOrder(self.file_list, self.file_add)
        Dialog.setTabOrder(self.file_add, self.file_del)
        Dialog.setTabOrder(self.file_del, self.sea_mask)
        Dialog.setTabOrder(self.sea_mask, self.sea_size_op)
        Dialog.setTabOrder(self.sea_size_op, self.sea_size)
        Dialog.setTabOrder(self.sea_size, self.sea_run)
        Dialog.setTabOrder(self.sea_run, self.sea_res)
        Dialog.setTabOrder(self.sea_res, self.sea_down)
        Dialog.setTabOrder(self.sea_down, self.down_list)
        Dialog.setTabOrder(self.down_list, self.down_del)
        Dialog.setTabOrder(self.down_del, self.down_finish_clear)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Yadon P2P (разработчик: студент группы 642 РГРТУ Акинин М.В.)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/image/gerb.png\" /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Рязанский государственный радиотехнический университет</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Кафедра Информационной безопасности</p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Клиент файлообменной сети \"YadonP2P\"</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">разработан в рамках курсового проекта</p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">\"Применение реляционных баз данных</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">в программном обеспечении файлообменных сетей\"</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">по дисциплине</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\"Системы управления базами данных\"</p>\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Разработчик:</p>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">студент группы 642 РГРТУ</p>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Акинин М.В.</p>\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Проверил:</p>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">старший преподователь кафедры ИБ</p>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Калинкина Т.И.</p>\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Рязань 2010</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), QtGui.QApplication.translate("Dialog", "О программе", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Настройка", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Локальный интерфейс", None, QtGui.QApplication.UnicodeUTF8))
        self.conf_host.setInputMask(QtGui.QApplication.translate("Dialog", "000.000.000.000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.conf_host.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.conf_host_all.setText(QtGui.QApplication.translate("Dialog", "Все", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("Dialog", "Локальные порты", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "MySQL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Route", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Upload", None, QtGui.QApplication.UnicodeUTF8))
        self.conf_mysql.setInputMask(QtGui.QApplication.translate("Dialog", "0000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.conf_route.setInputMask(QtGui.QApplication.translate("Dialog", "0000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.conf_upload.setInputMask(QtGui.QApplication.translate("Dialog", "0000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("Dialog", "Локальная база данных", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "База данных", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "Пользователь", None, QtGui.QApplication.UnicodeUTF8))
        self.conf_reset.setText(QtGui.QApplication.translate("Dialog", "Перечитать конфигурационный файл", None, QtGui.QApplication.UnicodeUTF8))
        self.start.setText(QtGui.QApplication.translate("Dialog", "Запуск сервера", None, QtGui.QApplication.UnicodeUTF8))
        self.stop.setText(QtGui.QApplication.translate("Dialog", "Останов сервера", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "Управление", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Соседние узлы", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Добавление соседнего узла", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "IP-адрес", None, QtGui.QApplication.UnicodeUTF8))
        self.host_ip.setInputMask(QtGui.QApplication.translate("Dialog", "000.000.000.000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.host_ip.setText(QtGui.QApplication.translate("Dialog", "127.0.0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Порт route-сервера", None, QtGui.QApplication.UnicodeUTF8))
        self.host_port.setInputMask(QtGui.QApplication.translate("Dialog", "0000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.host_port.setText(QtGui.QApplication.translate("Dialog", "7777", None, QtGui.QApplication.UnicodeUTF8))
        self.host_connect.setText(QtGui.QApplication.translate("Dialog", "Подключиться", None, QtGui.QApplication.UnicodeUTF8))
        self.host_disconnect.setText(QtGui.QApplication.translate("Dialog", "Отключиться", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QtGui.QApplication.translate("Dialog", "Сеть", None, QtGui.QApplication.UnicodeUTF8))
        self.file_add.setText(QtGui.QApplication.translate("Dialog", "Добавить файл", None, QtGui.QApplication.UnicodeUTF8))
        self.file_del.setText(QtGui.QApplication.translate("Dialog", "Удалить файл", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Dialog", "Мои файлы", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Dialog", "Критерии поиска", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Маска имени", None, QtGui.QApplication.UnicodeUTF8))
        self.sea_mask.setText(QtGui.QApplication.translate("Dialog", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Размер", None, QtGui.QApplication.UnicodeUTF8))
        self.sea_size_op.setItemText(0, QtGui.QApplication.translate("Dialog", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.sea_size_op.setItemText(1, QtGui.QApplication.translate("Dialog", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.sea_size_op.setItemText(2, QtGui.QApplication.translate("Dialog", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.sea_size_op.setItemText(3, QtGui.QApplication.translate("Dialog", ">=", None, QtGui.QApplication.UnicodeUTF8))
        self.sea_size_op.setItemText(4, QtGui.QApplication.translate("Dialog", "<=", None, QtGui.QApplication.UnicodeUTF8))
        self.sea_size_op.setItemText(5, QtGui.QApplication.translate("Dialog", "<>", None, QtGui.QApplication.UnicodeUTF8))
        self.sea_size.setInputMask(QtGui.QApplication.translate("Dialog", "0000000000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.sea_size.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "байт", None, QtGui.QApplication.UnicodeUTF8))
        self.sea_run.setText(QtGui.QApplication.translate("Dialog", "Поиск", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("Dialog", "Результаты поиска", None, QtGui.QApplication.UnicodeUTF8))
        self.sea_down.setText(QtGui.QApplication.translate("Dialog", "Скачать", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("Dialog", "Поиск", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Dialog", "Скачиваются", None, QtGui.QApplication.UnicodeUTF8))
        self.down_del.setText(QtGui.QApplication.translate("Dialog", "Удалить файл", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Dialog", "Скачивание завершено", None, QtGui.QApplication.UnicodeUTF8))
        self.down_finish_clear.setText(QtGui.QApplication.translate("Dialog", "Очистить список", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("Dialog", "Скачиваемые файлы", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">(Для обновления табличных представлений нажмите клавишу \'R\')</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))

import resource_rc
